# debe ser unico por instancia de SonarQube
sonar.projectKey=anthonycruzsulcaray_reto-swapi-node-aws
# Organization del proyecto en SonarCloud
sonar.organization=reto-swapi-node-aws
# Nombre del proyecto que se mostrara en la web
sonar.projectName=reto-swapi-node-aws
sonar.projectVersion=1.0

# Directorio donde se encuentra el código
sonar.sources=src
sonar.tests=test
# Exclusión de archivos
sonar.exclusions=src/serverlesDeploy/**/*
sonar.language=ts

# Encoding
sonar.sourceEncoding=UTF-8
sonar.typescript.jstest.reportPaths=coverage/lcov-report
sonar.typescript.lcov.reportPaths=coverage/lcov.info 
# Exclusión de coverage
sonar.coverage.exclusions=\
  src/utils/*,\
  src/validation/*,\
  src/api/**/*,\
  src/db/**/*,\
  src/repository/**/*,\
  src/module/api/**

